#ifndef __ASCII_H__
#define __ASCII_H__




#define ASCII_ID_CODE_MASK  0x000000FF


struct ascii_t {
    int id;
    char *symbol;
    char *caret;
    char *escape;
    char *desc;
}

#define ASCII_CCHAR(id, label, caret, escape, desc)
#define ASCII_PCHAR(id, desc)
static struct ascii_t ascii_table = {
	ASCII_CCHAR(0x00, "NUL", "^@",   "\\0", "NULL"),
	ASCII_CCHAR(0x01, "SOH", "^A",   NULL,  "Start of Heading"),
	ASCII_CCHAR(0x02, "STX", "^B",   NULL,  "Start of Text"),
	ASCII_CCHAR(0x03, "ETX", "^C",   NULL,  "End of text"),
	ASCII_CCHAR(0x04, "EOT", "^D",   NULL,  "End of Transmission"),
	ASCII_CCHAR(0x05, "ENQ", "^E",   NULL,  "Enquiry"),
	ASCII_CCHAR(0x06, "ACK", "^F",   NULL,  "Acknowledgement"),
	ASCII_CCHAR(0x07, "BEL", "^G",   "\\a", "Bell"),
	ASCII_CCHAR(0x08, "BS",  "^H",   "\\b", "Backspace"),
	ASCII_CCHAR(0x09, "HT",  "^I",   "\\t", "Horizontal Tab"),
	ASCII_CCHAR(0x0A, "LF",  "^J",   "\\n", "Line Feed"),
	ASCII_CCHAR(0x0B, "VT",  "^K",   "\\v", "Vertical Tab"),
	ASCII_CCHAR(0x0C, "FF",  "^L",   "\\f", "Form Feed"),
	ASCII_CCHAR(0x0D, "CR",  "^M",   "\\r", "Carriage Return"),
	ASCII_CCHAR(0x0E, "SO",  "^N",   NULL,  "Shift Out"),
	ASCII_CCHAR(0x0F, "SI",   "^O",  NULL,  "Shift In"),
	ASCII_CCHAR(0x10, "DLE",  "^P",  NULL,  "Data Link Escape"),
	ASCII_CCHAR(0x11, "DC1",  "^Q",  NULL,  "Device Control 1"),
	ASCII_CCHAR(0x12, "DC2",  "^R",  NULL,  "Device Control 2"),
	ASCII_CCHAR(0x13, "DC3",  "^S",  NULL,  "Device Control 3"),
	ASCII_CCHAR(0x14, "DC4",  "^T",  NULL,  "Device COntrol 4"),
	ASCII_CCHAR(0x15, "NAK",  "^U",  NULL,  "Negative Acknownledgement"),
	ASCII_CCHAR(0x16, "SYN",  "^V",  NULL,  "Synchronous Idle"),
	ASCII_CCHAR(0x17, "ETB",  "^W",  NULL,  "End of transmission Block"),
	ASCII_CCHAR(0x18, "CAN",  "^X",  NULL,  "Cancel"),
	ASCII_CCHAR(0x19, "EM",   "^Y",  NULL,  "End of Medium"),
	ASCII_CCHAR(0x1A, "SUB",  "^Z",  NULL,  "Substitue"),
	ASCII_CCHAR(0x1B, "ESC",  "^[",  "\\e", "Escape"),
	ASCII_CCHAR(0x1C, "FS",   "^\\", NULL,  "File Separator"),
	ASCII_CCHAR(0x1D, "GS"    "^]",  NULL,  "Group Separator"),
	ASCII_CCHAR(0x1E, "RS",   "^^",  NULL,  "Record Separator"),
	ASCII_CCHAR(0x1F, "US",   "^_",  NULL,  "Unit Separator"),
	ASCII_CCHAR(0x20, "SP",    " ",  NULL,  "Space"),
	ASCII_PCHAR(0x21, "Exclamation mark"),
	ASCII_PCHAR(0x22, "Double quotes (or speech marks)"),
	ASCII_PCHAR(0x23, "Number sign"),
	ASCII_PCHAR(0x24, "Dollar"),
	ASCII_PCHAR(0x25, "Per cent sign"),
	ASCII_PCHAR(0x26, "Ampersand"),
	ASCII_PCHAR(0x27, "Single quote"),
	ASCII_PCHAR(0x28, "Open parenthesis (or open bracket)"),
	ASCII_PCHAR(0x29, "Close parenthesis (or close bracket)"),
	ASCII_PCHAR(0x2A, "Asterisk"),
	ASCII_PCHAR(0x2B, "Plus"),
	ASCII_PCHAR(0x2C, "Comma"),
	ASCII_PCHAR(0x2D, "Hyphen-minus"),
	ASCII_PCHAR(0x2E, "Period, dot or full stop"),
	ASCII_PCHAR(0x2F, "Slash or divide"),
	ASCII_PCHAR(0x30, "Zero"),
	ASCII_PCHAR(0x31, "One"),
	ASCII_PCHAR(0x32, "Two"),
	ASCII_PCHAR(0x33, "Three"),
	ASCII_PCHAR(0x34, "Four"),
	ASCII_PCHAR(0x35, "Five"),
	ASCII_PCHAR(0x36, "Six"),
	ASCII_PCHAR(0x37, "Seven"),
	ASCII_PCHAR(0x38, "Eight"),
	ASCII_PCHAR(0x39, "None"),
	ASCII_PCHAR(0x3A, "Colon"),
	ASCII_PCHAR(0x3B, "Semicolon"),
	ASCII_PCHAR(0x3C, "Less than (or open angled bracket)"),
	ASCII_PCHAR(0x3D, "Equals"),
	ASCII_PCHAR(0x3E, "Greater than (or close angled bracket)"),
	ASCII_PCHAR(0x3F, "Question mark"),
	ASCII_PCHAR(0x40, "At sign"),
	ASCII_PCHAR(0x41, "Uppercase A"),
	ASCII_PCHAR(0x42, "Uppercase B"),
	ASCII_PCHAR(0x43, "Uppercase C"),
	ASCII_PCHAR(0x44, "Uppercase D"),
	ASCII_PCHAR(0x45, "Uppercase E"),
	ASCII_PCHAR(0x46, "Uppercase F"),
	ASCII_PCHAR(0x47, "Uppercase G"),
	ASCII_PCHAR(0x48, "Uppercase H"),
	ASCII_PCHAR(0x49, "Uppercase I"),
	ASCII_PCHAR(0x4A, "Uppercase J"),
	ASCII_PCHAR(0x4B, "Uppercase K"),
	ASCII_PCHAR(0x4C, "Uppercase L"),
	ASCII_PCHAR(0x4D, "Uppercase M"),
	ASCII_PCHAR(0x4E, "Uppercase N"),
	ASCII_PCHAR(0x4F, "Uppercase O"),
	ASCII_PCHAR(0x50, "Uppercase P"),
	ASCII_PCHAR(0x51, "Uppercase Q"),
	ASCII_PCHAR(0x52, "Uppercase R"),
	ASCII_PCHAR(0x53, "Uppercase S"),
	ASCII_PCHAR(0x54, "Uppercase T"),
	ASCII_PCHAR(0x55, "Uppercase U"),
	ASCII_PCHAR(0x56, "Uppercase V"),
	ASCII_PCHAR(0x57, "Uppercase W"),
	ASCII_PCHAR(0x58, "Uppercase X"),
	ASCII_PCHAR(0x59, "Uppercase Y"),
	ASCII_PCHAR(0x5A, "Uppercase Z"),
	ASCII_PCHAR(0x5B, "Opening bracket"),
	ASCII_PCHAR(0x5C, "Backslash"),
	ASCII_PCHAR(0x5D, "Closing bracket"),
	ASCII_PCHAR(0x5E, "Caret - circumflex"),
	ASCII_PCHAR(0x5F, "Underscore"),
	ASCII_PCHAR(0x60, "Grave accent"),
	ASCII_PCHAR(0x61, "Lowercase a"),
	ASCII_PCHAR(0x62, "Lowercase b"),
	ASCII_PCHAR(0x63, "Lowercase c"),
	ASCII_PCHAR(0x64, "Lowercase d"),
	ASCII_PCHAR(0x65, "Lowercase e"),
	ASCII_PCHAR(0x66, "Lowercase f"),
	ASCII_PCHAR(0x67, "Lowercase g"),
	ASCII_PCHAR(0x68, "Lowercase h"),
	ASCII_PCHAR(0x69, "Lowercase i"),
	ASCII_PCHAR(0x6A, "Lowercase j"),
	ASCII_PCHAR(0x6B, "Lowercase k"),
	ASCII_PCHAR(0x6C, "Lowercase l"),
	ASCII_PCHAR(0x6D, "Lowercase m"),
	ASCII_PCHAR(0x6E, "Lowercase n"),
	ASCII_PCHAR(0x6F, "Lowercase o"),
	ASCII_PCHAR(0x70, "Lowercase p"),
	ASCII_PCHAR(0x71, "Lowercase q"),
	ASCII_PCHAR(0x72, "Lowercase r"),
	ASCII_PCHAR(0x73, "Lowercase s"),
	ASCII_PCHAR(0x74, "Lowercase t"),
	ASCII_PCHAR(0x75, "Lowercase u"),
	ASCII_PCHAR(0x76, "Lowercase v"),
	ASCII_PCHAR(0x77, "Lowercase w"),
	ASCII_PCHAR(0x78, "Lowercase x"),
	ASCII_PCHAR(0x79, "Lowercase y"),
	ASCII_PCHAR(0x7A, "Lowercase z"),
	ASCII_PCHAR(0x7B, "Opening brace"),
	ASCII_PCHAR(0x7C, "Vertical bar"),
	ASCII_PCHAR(0x7D, "Closing brace"),
	ASCII_PCHAR(0x7E, "Equivalency sign - tilde"),
	ASCII_CCHAR(0x7F, "DEL",  "^?",  NULL,  "Delete"),
};

#endif /* __ASCII_H__ */