
TOPDIR ?= $(CURDIR)


include $(TOPDIR)/rule.mk
# =========================================================================== #

string-objs := mac_address.o

# $(eval $(call build, object, relocatable, string))

# =========================================================================== #
include $(TOPDIR)/toplevel.mk
