
TOPDIR ?= $(CURDIR)

include $(TOPDIR)/rule.mk
# =========================================================================== #

CFLAGS := -std=c99

$(eval $(call build, object, executable, main))

# =========================================================================== #
include $(TOPDIR)/toplevel.mk
